### ISSUE TITLE
The "Splunk Enterprise: Python Debugger" is not available

### ISSUE THREAD

**Issue by Jalkar** [splunk/vscode-extension-splunk#11]
I might have missed something, but the debugging configuration never appeared in debugging list. So I can never choose "Splunk Enterprise: Python Debugger" 

I'm trying to follow the wiki procedure.

"a debug configuration created by the supported add-on" it did not worked.

I've tried to uninstall/install with no success

**Comment by JasonConger** [comment]
Did you install the [Supporting Add-on](https://splunkbase.splunk.com/app/4801/) on your Splunk Enterprise server?

**Comment by Jalkar** [comment]
Yes it was installed and running...

**Comment by JasonConger** [comment]
What are you debugging on the Splunk side (add-on, custom search command, custom REST handler, etc.)?  Can you share a snippet of your code where you import the debugging library?  Something like the following:

```
import sys, os
sys.path.append(os.path.join(os.environ['SPLUNK_HOME'],'etc','apps','SA-VSCode','bin'))
import splunk_debug as dbg
dbg.enable_debugging(timeout=25)
```

Do you see anything when running the following search in Splunk?

`index=_internal error splunk_debug`

**Comment by roelblyweert** [comment]
I have the same problem. The command is not available and I did not find anything in the _internal index according to the query mentioned above. I tried to apply some debugging capabilities to one of the sample custom search commands (just to get to know the debugging capabilities of the VS code extension for Splunk). Code located here: https://github.com/splunk/splunk-sdk-python/tree/master/examples/searchcommands_app/package

However, the problem in my case is broader I think. I tried to get the extension up and running locally (on my mac), in a VM and in a docker container, but none of them was working. I followed the steps in the Splunk extension debugging pages on github and I configured a token on the Splunk instance. I always get the following error messages in VS code:
`Command 'Splunk: Run Saved Search' resulted in an error (reject is not defined)
The URL specified for the Splunk REST API is incorrect. Please check your settings.`

I don't really understand why it mentions that the Splunk REST API URL is incorrect, because it was always a clean Splunk install without any tunables.

**Comment by Jalkar** [comment]
So I had time to retry the procedure from the wiki : https://github.com/splunk/vscode-extension-splunk/wiki/Debugging

Does this procedure allow a remote connection or not ? Where do I configure the address for Splunk ?
Or do we have to merge with the "debug over ssh"

the procedure are not clear at all...

I do not have the python debug displayed in my VScode.

I also tryed the ssh remote procedure from the wiki : https://github.com/splunk/vscode-extension-splunk/wiki/Remote-Debugging-using-SSH

Same issue, i do not have any python debugging option.

When doing the procedure, vscode asked for my python interpreter. which path should I add ? Can this be the reason If it's not the python from splunk ?

**Comment by Jalkar** [comment]
Ok I managed to get it working by changing 2 things in my setup :

- forcing the interpreter to the splunk python3 via the `.vscode/settings.conf`
- creating the `SPLUNK_HOME` env variable on my env which was not set globally

**Comment by JasonConger** [comment]
Thanks for the followup @Jalkar .  FWIW, forcing the Python version in `settings.conf` is not a necessary step to get the debugger working.  The `SPLUNK_HOME` thing is curious as that env variable should get set by Splunk on start up.

**Comment by roelblyweert** [comment]
I don't get why this issue is closed. I still have the same problem and did not manage to get it working. I completely wiped all VS Code settings, the Splunk Enterprise install is a new one, so I don't see what is going wrong. 

When I read the comments above, I have some questions:
- What do you mean with setting the SPLUNK_HOME variable? Do we need to set it in launch.json as an environment variable in VS Code or somewhere else? Furthermore, it is apparently not needed to do this?
- When I see the configs above to force the python interpret, it seems that it was tested for a local Splunk install. I suppose that remote installs (over SSH) are working as well since part of the wiki covers this?

**Comment by Jalkar** [comment]
No i test it on a Remote install with docker, i force the python interpreter to use splunk python to be sure to have all the package/conf for my debugger

for the SPLUNK_HOME variable, I put it manually in the .bashrc of my user running splunk : `export SPLUNK_HOME=/opt/splunk`

**Comment by kostyantin2216** [comment]
Hey, sorry but i do not understand how this issue is closed, there is no "Splunk Enterprise: Python Debugger" and not only did i follow all the instructions i also had a look at the source code of this extension and read about debugger extensions [here](https://code.visualstudio.com/api/extension-guides/debugger-extension#anatomy-of-the-package.json-of-a-debugger-extension) and this extension does not seem to support debug configurations since from what i understood it has to be defined in `package.json` under the debugger section under contributes section, from what i understood in your documentation this extension should create a section in the `launch.json` file for debugging the splunk instance but there is nothing in the source code that does this, can someone please clear this up for me?

**Comment by JasonConger** [comment]
@kostyantin2216 to debug Python code running in Splunk, you will need to install the [Microsoft Visual Studio Code Supporting Add-on for Splunk](https://splunkbase.splunk.com/app/4801/) where the code you want to debug resides.
Next, add the following lines to the code you would like to debug:
```
import sys, os
sys.path.append(os.path.join(os.environ['SPLUNK_HOME'],'etc','apps','SA-VSCode','bin'))
import splunk_debug as dbg
dbg.enable_debugging(timeout=25)
```
For illustration purposes, let's say you are trying to debug a modular input.  You would add the above lines to your modular input code, then start your modular input (I usually do this by disabling/re-enabling the input).  When your modular input code runs with the above lines added, a `launch.json` file will be created in a hidden `.vscode` directory in the root of your Splunk app that contains the modular input.  For example, if your modular input code is in `$SPLUNK_HOME/etc/apps/my_app/bin/my_input.py` , the `launch.json` file will be created in `$SPLUNK_HOME/etc/apps/my_app/.vscode/launch.json`

The `dbg.enable_debugging(timeout=25)` line above will pause your input for 25 seconds waiting for the debugger to attach (if the debugger does not attach, the execution will continue as usual).  To attach the debugger, open your Splunk app folder in Visual Studio Code ( `$SPLUNK_HOME/etc/apps/my_app` from the above example).  Then, start your debugger and the Splunk debug configuration should be visible.

https://github.com/splunk/vscode-extension-splunk/wiki/Debugging

**Comment by kostyantin2216** [comment]
@JasonConger Thank you for the quick reply!

I am trying to debug a custom splunk command on a remote machine from my local machine.

I have gone through the Debug Walk through and its great and clear, i got confused at the end [here](https://github.com/splunk/vscode-extension-splunk/wiki/Debugging#starting-the-visual-studio-code-debugger), the splunk app folder i want to debug is on the remote machine and my local machine does not have splunk installed only the python code and conf files that are later copied to a splunk-docker image which is used on the remote machine.

So if i understand correctly from your explanation i would need to copy the `launch.json` from the remote machine to my local machine and add it to my project where VSCode is open? Or would i need to use [this](https://code.visualstudio.com/docs/remote/ssh) VSCode feature to open the splunk app folder on the remote machine?

**Comment by JasonConger** [comment]
@kostyantin2216 you will need the [Remote SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) for VS Code.

Here is what I do for debugging a remote Splunk instance with VS Code on my local machine:

- Install the [Microsoft Visual Studio Code Supporting Add-on for Splunk](https://splunkbase.splunk.com/app/4801/) on the remote Splunk instance
- Connect to the remote Splunk instance from [Visual Studio Code using SSH](https://github.com/splunk/vscode-extension-splunk/wiki/Remote-Debugging-using-SSH#step-2--connect-to-the-remote-splunk-enterprise-instance-from-visual-studio-code)
- [Open the the root app folder](https://github.com/splunk/vscode-extension-splunk/wiki/Remote-Debugging-using-SSH#step-3--open-the-root-folder-of-your-splunk-app) containing the code for your custom search command.  For example `/opt/splunk/etc/apps/my_custom_search_command`
- Add the following to your custom search command code:

```
import sys, os
sys.path.append(os.path.join(os.environ['SPLUNK_HOME'],'etc','apps','SA-VSCode','bin'))
import splunk_debug as dbg
dbg.enable_debugging(timeout=25)
```
- Run your custom search command on the remote Splunk instance.  When your custom search command runs, it will create the "Splunk Enterprise: Python Debugger" configuration if it isn't already there.
- Start the debugger in VS Code

Note: custom search commands typically run through 2 times - once for introspection and again for actually executing the command.  That being said, you may have to start the debugger more than once.

Note 2: placing the following line of code in your custom search command will force a breakpoint:
`dbg.set_breakpoint()`

https://github.com/splunk/vscode-extension-splunk/wiki/Remote-Debugging-using-SSH

**Comment by breid1313** [comment]
I'm experiencing this issue as well. The "Splunk Enterprise: Python Debugger" is not population. Additionally, adding
```
import sys, os
sys.path.append(os.path.join(os.environ['SPLUNK_HOME'],'etc','apps','SA-VSCode','bin'))
import splunk_debug as dbg
dbg.enable_debugging(timeout=25)
```
to my module breaks the app and my request in splunk that calls the module times out.

**Comment by rgalloway3** [comment]
I, too, am perplexed by this.  I have the app installed on Splunk and the VSCode extension installed.  Splunk is on my workstation so I shouldn't need to use ssh.  I have added `dbg.enabled_debugging` and `dbg.set_breakpoint` to my code.  I can see the .vscode/launch.json file is created, but still never see "Splunk Enterprise: Python Debugger" as an option in VS Code.  Re-launching VS Code every time I debug doesn't help, either.
I've noticed the Splunk Explorer never shows any saved searches or reports.  Could this be related?

**Comment by breid1313** [comment]
@rgalloway3 could you share the launch.json file that gets created? I have not gotten that to show up in vscode for me yet so maybe that would be helpful

**Comment by rgalloway3** [comment]
Here is my launch.json file.  I don't know how much help it will be since I can't debug at this point.

`{
    "configurations": [
        {
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "${workspaceFolder}"
                }
            ],
            "name": "Splunk Enterprise: Python Debugger",
            "request": "attach",
            "type": "python",
            "port": 5686
        }
    ],
    "version": "0.2.0"
}`

**Comment by rgalloway3** [comment]
I think I have it working now.  The secret, thanks to someone on Slack, is to open the app *folder* rather than the source file.  Then the .vscode/launch.json file is visible and can work it's magic.

**Comment by neeps** [comment]
If you have this error, you might also want to verify permissions on debug.conf and whether VSCode is selecting a Python 3.x runtime.

**Comment by SplunkerKV** [comment]
![error](https://user-images.githubusercontent.com/123500542/216423816-c3bba754-0e91-4940-927c-ae024c0959f0.PNG)
Getting this error

**Comment by SplunkerKV** [comment]
launch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Splunk Enterprise: Python Debugger",
            "type": "python",
            "request": "attach",
            "port": 5412,
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "${workspaceFolder}"
                }
            ]
        }
    ]
}

**Comment by SplunkerKV** [comment]
Fixed it. Silly mistake in debug.conf
Lines were commented out with * instead of #
