### ISSUE TITLE
Unable to connect to Splunk Web

### ISSUE THREAD

**Issue by lindonm** [splunk/vscode-extension-splunk#19]
Splunk Web does not allow the use of tokens for auth. We are using SAML (Azure) or can use local login.

Do you plan to ever support a username/password option (it would need to support Azure Modern Auth) ?

**Comment by JasonConger** [comment]
The token is used for REST API access rather than authenticating to Splunk Web.  Tokens can be used with native Splunk authentication (local login), LDAP, or SAML.  The Visual Studio Code extension uses this token to authenticate to the Splunk REST APIs to enumerate/run saved searches and embedded reports.  To create a new token, log on to your Splunk instance and navigate to Settings > Tokens.

**Comment by lindonm** [comment]
Apologies, I didn't mean "Splunk Web" I meant "Splunk Cloud" - There is no "Settings > Tokens" menu option, or "edit_tokens_settings" capability.

**Comment by JasonConger** [comment]
Ah - that makes sense.  There is some work getting triaged on the Splunk side to support token authentication for REST API access in Splunk Cloud -> https://ideas.splunk.com/ideas/PLECID-I-82

**Comment by JasonConger** [comment]
Token-Based Authentication for API Access in Cloud has shipped.

Reference -> https://ideas.splunk.com/ideas/PLECID-I-82
