### ISSUE TITLE
[bug] default stanza parameters gives linting error in indexes.conf

### ISSUE THREAD

**Issue by VatsalJagani** [splunk/vscode-extension-splunk#23]
[default] stanza parameters give the error in the listing. See the below screenshot.

![image](https://user-images.githubusercontent.com/20964366/87295378-b2f23880-c522-11ea-8500-ebcfcb290bd0.png)

I'm not sure if this issue persist with other conf files or not.

**Comment by JasonConger** [comment]
These settings `repFactor`, `frozenTimePeriodInSecs`, `maxHotSpanSecs`, etc. are all "per index options" [according the the .spec ](https://docs.splunk.com/Documentation/Splunk/latest/admin/indexesconf#PER_INDEX_OPTIONS).  So, the extension is treating them like individual index options rather than global options.  We'll look into handling this on the extension side though.

**Comment by vatsaljagani-crest** [comment]
@JasonConger  - I got that point but we can treat this a feature request. This would be really helpful for the developers.

**Comment by VatsalJagani** [comment]
True, I know the spec file is separated into two parts. But we can handle this on extension side. This would be really helpful for the developers.

**Comment by VatsalJagani** [comment]
Hi @JasonConger,
When I use the extension it does not show error on the last line in this file.
![image](https://user-images.githubusercontent.com/20964366/87458031-f46c0c00-c626-11ea-946b-fe89d92a6742.png)

But When I use debugging mode in VSCode, it shows the error. (I'm using develop branch on the repo)
![image](https://user-images.githubusercontent.com/20964366/87457967-dc948800-c626-11ea-959a-a47ad502e025.png)

Would you mind help me understand this?

**Comment by JasonConger** [comment]
Resolved in version 0.2.4
